alter table PIZZA_INGREDIENT add constraint FK_PIZZA_INGREDIENT_ON_TOPPING foreign key (TOPPING_ID) references PIZZA_TOPPING(ID);
create index IDX_PIZZA_INGREDIENT_ON_TOPPING on PIZZA_INGREDIENT (TOPPING_ID);
